reproducibility: True
data_path: data/recbole
show_progress: True

# Data Settings
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp

rm_dup_inter: False
user_inter_num_interval: "[0, inf)"
item_inter_num_interval: "[0, inf)"

# Training Settings_basic
epochs: 1000
train_batch_size: 128
learner: 'adam'
learning_rate: 0.001
neg_sampling: {'uniform': 1}
eval_step: 1
stopping_step: 10
loss_decimal_place: 4
weight_decay: 0.001

# Model settings
reg_weight: 250.0


#Evaluation Settings
eval_args:
    split: {"LS": "valid_and_test"}
    group_by: user
    order: RO
    mode: full
repeatable: False
metrics: ['Recall']
topk: 10
valid_metric: Recall@10
eval_batch_size: 4096
metric_decimal_place: 4
